config/routes.rb
Rails.application.routes.draw do
  resources :items do
    member do
      get :multi
      post :multi_save
    end
  end
  root "items#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :item_child
end

app/models/item_child.rb
class ItemChild < ActiveRecord::Base
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update, :destroy , :multi , :multi_save]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  def show
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to items_path, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  def multi
    @item_childs = ItemChild.where(:item_id => @item.id)
  end

  def multi_save
    #取出所有關連id
    ids = (params[:ic_old] || {}).keys.map{|i|i.to_i}

    #語意：排除送出的id之外的所有隸屬item的都刪除
    ItemChild.where("item_id = #{@item.id} AND id NOT IN (#{ids.join(',')})").delete_all

    #更新舊的資料
    if params[:ic_old]
      params[:ic_old].each_pair do |id , data|
        ic = ItemChild.where(:item_id => @item.id , :id => id).first
        if ic
          #這邊要過 permit 或是一個一個指定都行
          ic.update_attributes(:name => data[:name] , :age => data[:age])
        end
      end
    end

    #額外新增的都再塞入
    if params[:ic]
      params[:ic][:name].each_index do |index|
        ItemChild.create(:item_id => @item.id , :name => params[:ic][:name][index] , :age => params[:ic][:age][index])
      end
    end
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <%= link_to '<button>Back</button>'.html_safe, items_path %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to '<button>Show</button>'.html_safe, @item %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table border=1 cellpadding=5 cellspacing=0>
  <thead>
    <tr bgcolor=#CCC>
      <th>Name</th>
      <th>Child</th>
      <th colspan="4" align=center>Maintain</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td align=center><%= item.item_child.count %></td>
        <td><%= link_to 'Show', item_path(item) %></td>
        <td><%= link_to 'Multi', multi_item_path(item.id) %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button>New Item</button>'.html_safe, new_item_path %>

app/views/items/multi.html.erb
<% content_for :head do %>
<style>
  span{
    display:inline-block;
    margin:0 4px;
    border-radius:5px;
    padding:0 4px;
    cursor:pointer;
  }
  span.add{
    background:#cfc;
  }
  span.del{
    background:#fcc;
  }
  .template{
    display:none;
  }
  li{
    padding:2px 10px;
    margin:2px;
    background:#ffd;
    border:1px #dd6 solid;
    border-radius:10px;
  }
  li.old_record{
    background:#ddf;
    border-color:#66d;
  }
</style>
<script>
function bind_item(target){
  target.find('.add').click(function(){
    var temp = $('.template').clone().removeClass('template');
    temp.find("input , select").each(function(){
      $(this).attr('name' , $(this).attr('data-name'));
    });
    $('ol').append(bind_item(temp));
  }).siblings('.del').click(function(){
    if($('ol li').length > 2){
      $(this).parent('li').remove();
    }
  });
  return target;
}
jQuery(function($){
  bind_item($('ol li'));
  if($('ol li').length === 1){ //only template
    $('ol li .add').click();
  }
});
</script>
<% end %>

<h1>Multi : <%= @item.name %></h1>

<%= form_tag multi_save_item_path do %>
  <% age_list = (18..30).to_a %>
  <ol>
    <li class="template">name<input data-name="ic[name][]"> , age<select data-name="ic[age][]"><%= options_for_select(age_list) %></select><span class="add">add</span><span class="del">del</span></li>
    <% @item_childs.each do |old_ic| %>
      <li class="old_record">name<%= text_field_tag "ic_old[#{old_ic.id}][name]" , old_ic.name %> , age<%= select_tag "ic_old[#{old_ic.id}][age]" , options_for_select(age_list , old_ic.age) %></select><span class="add">add</span><span class="del">del</span> (<%= old_ic.id %>)</li>
    <% end %>
  </ol>
  <button type="submit">Submit</button>
  <%= link_to '<button>Back</button>'.html_safe, items_path %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Item Child:</strong>
  <ol>
    <% @item.item_child.each do |child| %>
    <li style='color:blue;'><%= "#{child.name} - #{child.age}" %></li>
    <% end %>
  </ol>
</p>

<%= link_to '<button>Edit</button>'.html_safe, edit_item_path(@item) %>
<%= link_to '<button>Back</button>'.html_safe, root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MultiRelation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>